from twython import Twython
from sqlite3 import connect, IntegrityError
from time import sleep

# Class for handling tweets
class Tweet (object):
	def __init__ (self, id, text):
		self.id = id
		self.text = text


def getTweets (term, total):
    # Keys that have been generated by Twitter
    consumer_key = "7nvOlZqscSZ7eC3TBckNtZsTR"
    consumer_secret = "qcX6CV7vKGncPXQmuV5tHPysBgnXOnh0Ll426MAGKT5vqDkWt1"
    access_token = "65634842-1JnWcq6x2l7Lz4QI5LUkElxIQqQayqYQm8N5lWjyR"
    access_token_secret = "CFzIsNeuUndGhOAmjulrLVpSvIcViONTzB4Et784htP3K"

    # Initialize Twython object
    twitter = Twython(consumer_key, consumer_secret, access_token, access_token_secret)

    # Search for tweets
    tweets = twitter.search(q=term, count=total, lang='en')

    # Return list of Tweet objects
    return [Tweet(tweet['id'], tweet['text']) for tweet in tweets['statuses']]